### ISSUE TITLE
Misc cleanups

### ISSUE THREAD

**Issue by kevin-dutra** [ndrake0027/drupaljunitparser#1]
https://github.com/ndrake0027/drupaljunitparser/blob/d1cdfd44fb49a14a33ff8c7f8553a4c5ad5b2bed/src/Parser.php#L9

The namespacing seems a little odd. I'd either expect this to be either a single top level item that describes the project (e.g. `DrupalJUnit`, so that invocations were `new \DrupalJUnit\Parser()`) or that the namespace was generic but the classname was specific (e.g. `new \JUnitParser\Parse\Drupal()`). Probably the first one is more expected.

https://github.com/ndrake0027/drupaljunitparser/blob/d1cdfd44fb49a14a33ff8c7f8553a4c5ad5b2bed/src/Parser.php#L14

Unused import?

https://github.com/ndrake0027/drupaljunitparser/blob/d1cdfd44fb49a14a33ff8c7f8553a4c5ad5b2bed/src/Parser.php#L20

Class comment block looks like it's actually supposed to be for the `parse()` method. So a proper class comment needs to be added and the method comment needs to be augmented a bit to be more descriptive and cover all the parameters.

https://github.com/ndrake0027/drupaljunitparser/blob/d1cdfd44fb49a14a33ff8c7f8553a4c5ad5b2bed/src/Parser.php#L56

It seems like you actually need to encapsulate the `Serializer` instantiation within this class. You rely on the fact that it has the XML encoder within this class, but unless you add that yourself here, there's no guarantee that the XML encoder is even available to work with.

https://github.com/ndrake0027/drupaljunitparser/blob/d1cdfd44fb49a14a33ff8c7f8553a4c5ad5b2bed/src/Parser.php#L65
https://github.com/ndrake0027/drupaljunitparser/blob/d1cdfd44fb49a14a33ff8c7f8553a4c5ad5b2bed/src/Parser.php#L72

`$type` can only be one thing, so it makes sense to either turn these second conditionals into `elseif` or switch the control structures to `switch` statements to short circuit if the first condition ends up being true.

https://github.com/ndrake0027/drupaljunitparser/blob/d1cdfd44fb49a14a33ff8c7f8553a4c5ad5b2bed/src/Parser.php#L70
https://github.com/ndrake0027/drupaljunitparser/blob/d1cdfd44fb49a14a33ff8c7f8553a4c5ad5b2bed/src/Parser.php#L73

These private methods only ever use the data from `$this->report`, so it's a little odd that they take it as an argument. I'd suggest that either the `build` methods just directly make use of the `report` class member or that the `parse` methods return the data that is then passed into the `build` methods via a method argument.

https://github.com/ndrake0027/drupaljunitparser/blob/d1cdfd44fb49a14a33ff8c7f8553a4c5ad5b2bed/src/Parser.php#L75

Rather than tacking on the extra ending HTML tags, it would be cleaner to include the full HTML as the constant with some sort of token for where you want to inject the real content. Then you can just do a `str_replace()` to inject the content. (This would even allow you to pull the HTML out of the class entirely and just have it in a standalone HTML file, if you wanted to get carried away.)

https://github.com/ndrake0027/drupaljunitparser/blob/d1cdfd44fb49a14a33ff8c7f8553a4c5ad5b2bed/src/Parser.php#L83
https://github.com/ndrake0027/drupaljunitparser/blob/d1cdfd44fb49a14a33ff8c7f8553a4c5ad5b2bed/src/Parser.php#L109
https://github.com/ndrake0027/drupaljunitparser/blob/d1cdfd44fb49a14a33ff8c7f8553a4c5ad5b2bed/src/Parser.php#L124
https://github.com/ndrake0027/drupaljunitparser/blob/d1cdfd44fb49a14a33ff8c7f8553a4c5ad5b2bed/src/Parser.php#L137

Again, method comment blocks are a little lacking. 😁 

https://github.com/ndrake0027/drupaljunitparser/blob/d1cdfd44fb49a14a33ff8c7f8553a4c5ad5b2bed/src/Parser.php#L142

You can probably save yourself a little trouble by storing the scenario states in a specific bucket, so that it's easier to pull out only what you want. (Rather than checking if the item you're looking at is an array.) i.e.
```$this->report[$testsuite['@name']]['stats'] = [ ...blah...```
Then this loop could be simplified down to
```
foreach ($node['stats'] as $key => $value) {
  $this->html .= '<tr><td>' . $key . '</td><td>' . $value . '</td></tr>';
}
```

https://github.com/ndrake0027/drupaljunitparser/blob/d1cdfd44fb49a14a33ff8c7f8553a4c5ad5b2bed/src/Parser.php#L150

This is kinda weird. Since we always need one, how about we just do it outside the loop? That way we don't have this `$header` flag thingy. e.g.
```
$this->html .= '</table><br><table>';
if( count($node)) {
  $this->html .= '<tr><th>' . implode('</th><th>', array_keys($node[0])) . '</th></tr>';
}
foreach ($node as $key => $test) {
```

**Comment by ndrake0027** [comment]
@kevin-dutra only question is about: 

> Rather than tacking on the extra ending HTML tags, it would be cleaner to include the full HTML as the constant with some sort of token for where you want to inject the real content. Then you can just do a str_replace() to inject the content. (This would even allow you to pull the HTML out of the class entirely and just have it in a standalone HTML file, if you wanted to get carried away.)

Can you explain a bit more here. 

All other changes have been made

**Comment by kevin-dutra** [comment]
Basically this:
```
  protected $html = '<html><head><style>
                     table, th, td {
                        border: 1px solid black;
                        border-collapse: collapse;
                      }
                      th, td {
                          padding: 5px;
                      }
                      th {
                          text-align: left;
                      }
                      </style>
                      </style></head><body>[content]</body></html>';

...
file_put_contents($path . '/' . $type . '_report.html', str_replace('[content]', $content, $this->html));
```

**Comment by ndrake0027** [comment]
@kevin-dutra I think the last of the issues here are fixed with the last push. Agree?

**Comment by kevin-dutra** [comment]
@ndrake0027 Pretty much. I think the only other thing was the comment about the serializer. Right now we're just accepting a serializer via the constructor and using it with the assumption that whoever gave it to us initialized it with the XML encoder.
```
  public function __construct(Serializer $serializer) {
    $this->serializer = $serializer;
  }

...

$xml = $this->serializer->decode($raw, 'xml');
```
So if you got passed a serializer that only got initialized with the JSON encoder, then bonk. The safer way would be to encapsulate the serializer within this class so that we know for sure what it has available. (It also makes this a little easier for the implementing code to use. i.e.
```
  public function __construct() {
    $encoders = [new Serializer\Encoder\XmlEncoder()];
    $normalizers = [new Serializer\Normalizer\ObjectNormalizer()];
    $this->serializer = new Serializer\Serializer($normalizers, $encoders);
  }
```
then the implementing code simplifies down to just
```
$parser = new Parser\Parser();
$parser->parse($dir, $pattern, $type);
```

Up to you whether you want to take it that extra step -- everything else looks good to me.

**Comment by ndrake0027** [comment]
Everything should be good now.
