### ISSUE TITLE
Warning messages about adding an attribute that already exists

### ISSUE THREAD

**Issue by kevin-dutra** [ndrake0027/drupaljunitparser#2]
https://github.com/ndrake0027/drupaljunitparser/blob/73730a0918dbaba44b5b7e116c21d1b058771f80/src/Parser/Parser.php#L308

We get fairly frequent warning messages at this line:
`Warning: SimpleXMLElement::addAttribute(): Attribute already exists in /var/www/community/vendor/ndrake0027/drupal-junit-parser/src/Parser/Parser.php on line 308`

It's trying to add an attribute to `$child`, but the surrounding condition is looking for whether it already exists on `$nest`. It's not 100% clear to me which one the attribute should really be going on, but at any rate, there's a mismatch.

**Comment by ndrake0027** [comment]
Removed the lines in the latest release.
